version: "3.9"
services:
  postgres:
    image: postgres:14.5
    env_file: .env

  node:
    build: ./
    env_file: .env
    depends_on:
      - postgres

  ngnix:
    image: nginx:stable
    depends_on:
      - node
      - postgres
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80